import { Inter } from "next/font/google";
import React from "react";
import "./globals.css";
// import { WebVitals } from './_components/web-vitals';
// import { NextWebVitals } from "nextlevelpackage";
import NextWebVitals from 'nextlevelpackage';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextWebVitals />
        {children}
        </body>
    </html>
  );
}
